# Generated by Django 4.1.5 on 2023-02-23 16:22

import core.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=254, validators=[core.validators.ValidateEmailDomain('gmail.com', 'yahoo.com', 'email.com')])),
                ('phone', models.CharField(max_length=19)),
                ('salary', models.PositiveIntegerField(default=10000)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
